import Head from "next/head";
import { Inter } from "@next/font/google";
import BottomNav from "@/Components/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid place-items-center h-screen">
        <div className="p-8 border border-secondary text-secondary text-center relative">
          <h1 className="text-4xl md:text-6xl">Work In Progress</h1>
          <h2 className="absolute -bottom-2.5 bg-primary px-6 left-1/2 -translate-x-1/2">
            Be Right Back!
          </h2>
        </div>
        <BottomNav />
      </main>
    </>
  );
}
